name: Playwright Smoke Tests

on:
  workflow_call:
    inputs:
      url:
        description: 'Base url to be used in tests'
        required: true
        type: string

jobs:
  smoke_test:
    name: â˜ï¸ Smoke test ${{ inputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2

      - name: ğŸ”¢ Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: ğŸ” Install dependencies
        run: npm ci

      - name: ğŸ­ Install Playwright
        run: npx playwright install --with-deps

      - name: ğŸ§ª Run Playwright tests
        run: npm run test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ inputs.url }}

      - name: ğŸ“¦ Upload Test Results Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-test-results
          path: playwright-report
